import { StyleSheet } from "react-native";

export const getStyles = (isDark) => StyleSheet.create({
  verticalContent: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 24,
    gap: 24,
    width: '100%',
  },
  page: {
    flex: 1,
    backgroundColor: isDark ? '#181a20' : '#f4f8fb',
  },
  header: {
    width: '100%',
    paddingTop: 48,
    paddingBottom: 16,
    backgroundColor: isDark ? '#23263a' : '#4A90E2',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  title: {
    color: '#fff',
    fontSize: 28,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 32,
    width: '100%',
  },
  horizontalContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    paddingHorizontal: 24,
    paddingVertical: 32,
    gap: 32,
  },
  activityColumn: {
    minWidth: 320,
    maxWidth: 400,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginHorizontal: 12,
  },
  inputCard: {
    marginTop: 32,
    backgroundColor: isDark ? '#23263a' : '#fff',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 360,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    alignItems: 'center',
  },
  label: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    color: isDark ? '#eee' : '#333',
    alignSelf: 'flex-start',
  },
  colorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 16,
  },
  colorButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginHorizontal: 6,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: isDark ? '#444' : '#ccc',
  },
  input: {
    borderWidth: 1,
    borderColor: isDark ? '#4A90E2' : '#4A90E2',
    borderRadius: 8,
    padding: 10,
    marginBottom: 16,
    marginTop: 4,
    width: '100%',
    fontSize: 16,
    backgroundColor: isDark ? '#23263a' : '#f7fafd',
    color: isDark ? '#fff' : '#222',
  },
});
